php artisan make:model AccountBanHistory
php artisan make:model AccountBans
php artisan make:model AccountViplist
php artisan make:model Accounts
php artisan make:model GuildInvites
php artisan make:model GuildMembership
php artisan make:model GuildRanks
php artisan make:model GuildWars
php artisan make:model Guilds
php artisan make:model GuildwarKills
php artisan make:model HouseLists
php artisan make:model Houses
php artisan make:model IpBans
php artisan make:model MarketHistory
php artisan make:model MarketOffers
php artisan make:model PlayerDeaths
php artisan make:model PlayerDepotitems
php artisan make:model PlayerInboxitems
php artisan make:model PlayerItems
php artisan make:model PlayerNamelocks
php artisan make:model PlayerSpells
php artisan make:model PlayerStorage
php artisan make:model Players
php artisan make:model PlayersOnline
php artisan make:model ServerConfig
php artisan make:model TileStore
php artisan make:model Znote
php artisan make:model ZnoteAccounts
php artisan make:model ZnoteChangelog
php artisan make:model ZnoteDeletedCharacters
php artisan make:model ZnoteForum
php artisan make:model ZnoteForumPosts
php artisan make:model ZnoteForumThreads
php artisan make:model ZnoteGlobalStorage
php artisan make:model ZnoteGuildWars
php artisan make:model ZnoteImages
php artisan make:model ZnoteNews
php artisan make:model ZnotePagseguro
php artisan make:model ZnotePagseguroNotifications
php artisan make:model ZnotePaygol
php artisan make:model ZnotePaypal
php artisan make:model ZnotePlayerReports
php artisan make:model ZnotePlayers
php artisan make:model ZnoteShop
php artisan make:model ZnoteShopLogs
php artisan make:model ZnoteShopOrders
php artisan make:model ZnoteTickets
php artisan make:model ZnoteTicketsReplies
php artisan make:model ZnoteVisitors
php artisan make:model ZnoteVisitorsDetails